<?php

/**
 * @file
 * GSB AZ filter.
 */

/**
 * Implements hook_library().
 */
function gsb_az_filter_library() {
  $libraries['gsb_az_filter'] = array(
    'title' => 'GSB AZ Filter',
    'website' => 'https://github.com/gsbitse/gsb_az_filter',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'gsb_az_filter') . '/js/gsb_az_filter.js' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form().
 */
function gsb_az_filter_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  // This is an array keyed by view machine name, with the value being the
  // name of the form item being replaced.
  $views = array(
    'faculty_filters' => 'last_name',
  );

  // If this view has a form item specified, and it exists in the form.
  if (isset($form[$views[$form_state['view']->name]])) {
    // Find the form item being replaced.
    $form_item_name = $views[$form_state['view']->name];

    // Determine the active letter, and remove it from the query string.
    $query = drupal_get_query_parameters();
    $active_letter = isset($query[$form_item_name]) ? $query[$form_item_name] : '';
    unset($query[$form_item_name]);

    // Make an array of all letters, starting with an 'All' reset link.
    $values[''] = t('All');
    $values += drupal_map_assoc(range('A', 'Z'));

    // Build an array of links.
    $links = array();
    foreach ($values as $letter => $text) {
      $links[$letter] = array(
        'title' => $text,
        'href' => '',
        'query' => $query,
        'external' => TRUE,
        'attributes' => array(
          'class' => array(
            'gsb-az-filter',
          ),
          'data-gsb-az-filter-letter' => $letter,
        ),
      );

      // If this is not the 'All' link, add the query string.
      if ($letter != '') {
        $links[$letter]['query'][$form_item_name] = $letter;
      }

      // Mark the active link.
      if ($active_letter == $letter) {
        $links[$letter]['attributes']['class'][] = 'active';
      }
    }

    // Add a new form element to display the A-Z list.
    $form["gsb_az_filter_$form_item_name"] = array(
      'prev' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'prev-next',
            'prev',
          ),
        ),
      ),
      'links' => array(
        '#theme' => 'links',
        '#links' => $links,
        '#attached' => array(
          'library' => array(
            array('gsb_az_filter', 'gsb_az_filter'),
          ),
          'js' => array(
            array(
              'type' => 'setting',
              'data' => array(
                'gsb_az_filter' => array(
                  'form_item_name' => $form_item_name,
                ),
              ),
            ),
          ),
        ),
      ),
      'next' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'enabled',
            'prev-next',
            'next',
          ),
        ),
      ),
    );

    // Replace the original element with a hidden value.
    $form[$form_item_name] = array(
      '#type' => 'hidden',
      '#default_value' => $active_letter,
    );

    // Tell Views that our filter exists.
    $form['#info']['filter-gsb-az-filter'] = array(
      'value' => "gsb_az_filter_$form_item_name",
    );
  }
}
